# Seção 2.1 - Estruturas de Dados

Este Notebook contém alguns exemplos retirados do livro-texto.

### Sequências

In [ ]:
texto = "Aprendendo Python na disciplina de linguagem de programação."
print(f"Tamanho do texto = {len(texto)}")
print(f"Python in texto = {'Python' in texto}")
print(f"Quantidade de y no texto = {texto.count('y')}")
print(f"As 5 primeiras letras são: {texto[0:6]}")

Tamanho do texto = 60
Python in texto = True
Quantidade de y no texto = 1
As 5 primeiras letras são: Aprend


In [ ]:
texto = "Aprendendo Python na disciplina de linguagem de programação."
print(texto.upper())
print(texto.replace("i", 'XX'))

APRENDENDO PYTHON NA DISCIPLINA DE LINGUAGEM DE PROGRAMAÇÃO.
Aprendendo Python na dXXscXXplXXna de lXXnguagem de programação.


### Listas

In [ ]:
vogais = ['a', 'e', 'i', 'o', 'u']
for vogal in vogais:
    print(f'Posição = {vogais.index(vogal)}, valor = {vogal}')

Posição = 0, valor = a
Posição = 1, valor = e
Posição = 2, valor = i
Posição = 3, valor = o
Posição = 4, valor = u


In [ ]:
vogais = []
print(f"Tipo do objeto vogais = {type(vogais)}")
vogais.append('a')
vogais.append('e')
vogais.append('i')
vogais.append('o')
vogais.append('u')
for p, x in enumerate(vogais):
    print(f"Posição = {p}, valor = {x}")

Tipo do objeto vogais = <class 'list'>
Posição = 0, valor = a
Posição = 1, valor = e
Posição = 2, valor = i
Posição = 3, valor = o
Posição = 4, valor = u


In [ ]:
frutas = ["maça", "banana", "uva", "mamão", "maça"]
notas = [8.7, 5.2, 10, 3.5]
print("maça" in frutas)  # True
print("abacate" in frutas)  # False
print("abacate" not in frutas)  # True
print(min(frutas))  # banana
print(max(notas))  # 10
print(frutas.count("maça"))  # 2
print(frutas + notas)
print(2 * frutas)

True
False
True
banana
10
2
['maça', 'banana', 'uva', 'mamão', 'maça', 8.7, 5.2, 10, 3.5]
['maça', 'banana', 'uva', 'mamão', 'maça', 'maça', 'banana', 'uva', 'mamão', 'maça']


In [ ]:
lista = ['Python', 30.61, "Java", 51, ['a', 'b', 20], "maça"]
print(f"Tamanho da lista = {len(lista)}")
for i, item in enumerate(lista):
    print(f"Posição = {i}, valor = {item} --> tipo"
          f" individual = {type(item)}")
print("\nExemplos de slices:\n")
print("lista[1] = ", lista[1])
print("lista[0:2] = ", lista[0:2])
print("lista[:2] = ", lista[:2])
print("lista[3:5] = ", lista[3:5])
print("lista[3:6] = ", lista[3:6])
print("lista[3:] = ", lista[3:])
print("lista[-2] = ", lista[-2])
print("lista[-1] = ", lista[-1])
print("lista[4][1] = ", lista[4][1])

Tamanho da lista = 6
Posição = 0, valor = Python --> tipo individual = <class 'str'>
Posição = 1, valor = 30.61 --> tipo individual = <class 'float'>
Posição = 2, valor = Java --> tipo individual = <class 'str'>
Posição = 3, valor = 51 --> tipo individual = <class 'int'>
Posição = 4, valor = ['a', 'b', 20] --> tipo individual = <class 'list'>
Posição = 5, valor = maça --> tipo individual = <class 'str'>

Exemplos de slices:

lista[1] =  30.61
lista[0:2] =  ['Python', 30.61]
lista[:2] =  ['Python', 30.61]
lista[3:5] =  [51, ['a', 'b', 20]]
lista[3:6] =  [51, ['a', 'b', 20], 'maça']
lista[3:] =  [51, ['a', 'b', 20], 'maça']
lista[-2] =  ['a', 'b', 20]
lista[-1] =  maça
lista[4][1] =  b


### map()

In [ ]:
linguagens = 'Python Java JavaScript C C# C++ Swift Go Kotlin'.split()

In [ ]:
linguagens

['Python', 'Java', 'JavaScript', 'C', 'C#', 'C++', 'Swift', 'Go', 'Kotlin']

In [ ]:
nova_lista = map(lambda x: x.lower(), linguagens)

In [ ]:
nova_lista

In [ ]:
list(nova_lista)

['python', 'java', 'javascript', 'c', 'c#', 'c++', 'swift', 'go', 'kotlin']

Outro exemplo

In [ ]:
def evaluate(x):
    print(x)

mymap = map(evaluate, [1,2,3]) # não imprime nada ainda
print(mymap)


next() retorna o próximo item de um iterador

In [ ]:
next(mymap)

1


In [ ]:

next(mymap)
next(mymap)
next(mymap)

2
3


StopIteration: ignored

### filter()

In [ ]:
num = list(range(21))

In [ ]:
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
a = filter(lambda x: x % 2 == 0, num)
a

In [ ]:
list(a)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

## Tuplas

- Tuplas são imutáveis

In [ ]:
tupla01 = ()  # tupla vazia
tupla01

()

In [ ]:
tupla01 = (1, 2, 3)
tupla01

(1, 2, 3)

In [ ]:
vogais = ('a', 'e', 'i', 'o', 'u')

enumerate() : qdo precisamos de um contador e um valor

In [ ]:
 for p, x in enumerate(vogais) :
    print(p, x)

0 a
1 e
2 i
3 o
4 u


## Set

- Armazena vários itens em uma única variável
- Não permite itens duplicados, não é ordenado, não é indexado, não pode ser alterado (porém pode ser eliminado ou adicionado)

In [ ]:
 set1 = {'a', 'b', 'c'}
 set1

{'a', 'b', 'c'}

In [ ]:
set1.add('a')
set1

{'a', 'b', 'c'}

In [ ]:
set1 = set(['a', 'b', 'c'])

In [ ]:
set1

{'a', 'b', 'c'}

### Dicionário

- Pode ser alterado, não pode duplicado.

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [ ]:
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [ ]:
thisdict['model']

'Mustang'

### Array NumPy

- NumPy é uma bilbioteca para computação científica, bastante utilizada.

In [ ]:
import numpy as np

matriz = np.array([[1, 2], [3, 4]])

In [ ]:
matriz

array([[1, 2],
       [3, 4]])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.eye(4)    # matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4).sum()  # também: min, máx, mean

4.0

In [ ]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [ ]:
numpy.ones((1,5)).reshape(5,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

<hr color='green' size=10>

### Biblioteca Pandas (introdução)

In [ ]:
import pandas as pd

In [ ]:
mydataset = {
  'carros': ["BMW", "Volvo", "Ford"],
  'passageiros': [3, 7, 2]
}

In [ ]:
mydataset

{'carros': ['BMW', 'Volvo', 'Ford'], 'passageiros': [3, 7, 2]}

In [ ]:
myvar = pd.DataFrame(mydataset)

In [ ]:
myvar

carros  passageiros
0    BMW            3
1  Volvo            7
2   Ford            2

In [ ]:
a = pd.Series([1, 7, 2])
a

0    1
1    7
2    2
dtype: int64

In [ ]:
a[0]

1

In [ ]:
a = [1, 7, 2]
myvar = pd.Series(a, index = ["x", "y", "z"])
myvar

x    1
y    7
z    2
dtype: int64

In [ ]:
myvar['y']

7

In [ ]:
myvar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  3 non-null      int64
 1   duration  3 non-null      int64
dtypes: int64(2)
memory usage: 176.0 bytes
